### PR TITLE
Main foreach loop simplification

### PR DESCRIPTION
**Pull request by drcoccodrillus**
I bumped into your repo while I was looking for a solution for generating XML address book for Yealink phones. Thank you, it's a very nice script! However, I have simplified the foreach loop logic. I tested on my FreePBX instances and it works fine. Have a look at it and let me know.

### CODE REVIEW

**Comment by sorvani** [comment]
i am out of town. I will look at it later this week. thanks for the PR

**Comment by drcoccodrillus** [comment]
No worries! Take your time mate.

**Comment by drcoccodrillus** [comment]
Hi mate! Did you get a chance for reviewing the pull request?

**Comment by sorvani** [comment]
Finally had a chance to test this. Thanks for the submission.

**Pull request merged**
